name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a feature request. Your feedback is invaluable in improving the Prisma Nuxt module.

        Please carefully read the [contribution guide](https://github.com/prisma/prisma-nuxt/blob/main/CONTRIBUTING.md) before submitting a new idea.
  - type: textarea
    attributes:
      label: What is the problem this feature would solve?
      description: Please provide a detailed description of the problem you are experiencing.
      placeholder: Describe the problem in detail...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the feature you are proposing to solve the problem
      description: Provide a detailed description of the feature you are proposing to address the problem.
      placeholder: Describe the proposed feature in detail...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
      description: Please describe any alternative solutions or features you have considered.
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed with this request.
      options:
        - label: Would you be willing to help implement this feature?
  - type: checkboxes
    id: final-checks
    attributes:
      label: Final checks
      description: Before submitting, please make sure you do the following
      options:
        - label: Read the [contribution guide](https://github.com/prisma/prisma-nuxt/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check existing [discussions](https://github.com/prisma/prisma-nuxt/discussions) and [issues](https://github.com/prisma/prisma-nuxt/issues) to ensure that this feature hasn't already been requested.
          required: true
